services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Himosh1020
      POSTGRES_DB: logistics_db
    ports:
      - "5432:5433"

  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:Himosh1020@db:5432/logistics_db
    depends_on:
      - db
    ports:
      - "8000:8000"
